steps:
- name: mcr.microsoft.com/playwright:v1.61.0-noble
  entrypoint: bash
  args:
    - "-c"
    - |
      npm install
      npx playwright install --with-deps
      npx playwright test

options:
  logging: CLOUD_LOGGING_ONLY

artifacts:
  objects:
    location: gs://playwright-report-bucket11/playwright-report
    paths:
      - playwright-report/**
      - test-results/**
